### ISSUE TITLE
Should raise/handle failures from remote_send

### ISSUE THREAD

**Issue by blueyed** [AndrewRadev/vimrunner#53]
```
% vim --servername foo --remote-expr bar
E247: no registered server named "FOO": Send expression failed.
```

I think this output on stderr should be handled and raised as an exception itself.

Currently it seems to result in an empty string, which might also compare to another remote expression equally then, which is also empty due to this.

I've noticed this with a segfaulting Vim due to https://github.com/vim/vim/commit/ad6480961080f80a455b2394f27b02935a2ded52.
The E247 appears on stderr at least, but the tests themselves were happily comparing two failing remote expressions as being equal.

Maybe any output on stderr should be raised?

**Comment by AndrewRadev** [comment]
That's a sensible idea. I've implemented it in https://github.com/AndrewRadev/vimrunner/commit/78f8fc983f8a861e81a65d5c539df70a5241b86c. I'm a bit worried if Vim outputs warnings or something to stderr, but if something like this happens, I guess someone will complain and I can check for `/E\d\+:/`.

Could you try it out and see if it catches your error?

**Comment by blueyed** [comment]
Thanks, it works:

```
FF
An error occurred in an `after(:suite)` hook.
Failure/Error: normal(':qall!<CR>')

Vimrunner::ExecutionError:
  Command failed (["vim", "--servername", "VIMRUNNER0.44506276436254566", "--remote-send", "<C-\\><C-n>:qall!<CR>"]), output: E247: no registered server named "VIMRUNNER0.44506276436254566": Send failed.
# ./spec/spec_helper.rb:26:in `kill'


Failures:

  1) vim for cython when using a cdef function definition indents shiftwidth spaces
     Failure/Error: vim.echo("indent('.')").to_i
     
     Vimrunner::ExecutionError:
       Command failed (["vim", "--servername", "VIMRUNNER0.44506276436254566", "--remote-expr", "VimrunnerEvaluateCommandOutput('echo indent(''.'')')"]), output: E247: no registered server named "VIMRUNNER0.44506276436254566": Send expression failed.
     # ./spec/spec_helper.rb:44:in `indent'
     # ./spec/indent/cython_spec.rb:22:in `block (3 levels) in <top (required)>'

  2) vim for cython when using a cpdef function definition indents shiftwidth spaces
     Failure/Error: raise ExecutionError.new("Command failed (#{command}), output: #{err}")
     
     Vimrunner::ExecutionError:
       Command failed (["vim", "--servername", "VIMRUNNER0.44506276436254566", "--remote-expr", "VimrunnerEvaluateCommandOutput('cd /tmp/d20180722-32065-javptg')"]), output: E247: no registered server named "VIMRUNNER0.44506276436254566": Send expression failed.
     # /home/user/.gem/ruby/2.5.0/bin/gems/vimrunner-0.3.4/lib/vimrunner/server.rb:174:in `execute'
     # /home/user/.gem/ruby/2.5.0/bin/gems/vimrunner-0.3.4/lib/vimrunner/server.rb:152:in `remote_expr'
     # /home/user/.gem/ruby/2.5.0/bin/gems/vimrunner-0.3.4/lib/vimrunner/client.rb:192:in `command'
     # /home/user/.gem/ruby/2.5.0/bin/gems/vimrunner-0.3.4/lib/vimrunner/rspec.rb:52:in `block (4 levels) in <top (required)>'
     # /home/user/.gem/ruby/2.5.0/bin/gems/vimrunner-0.3.4/lib/vimrunner/rspec.rb:51:in `chdir'
     # /home/user/.gem/ruby/2.5.0/bin/gems/vimrunner-0.3.4/lib/vimrunner/rspec.rb:51:in `block (3 levels) in <top (required)>'
     # /usr/lib/ruby/2.5.0/tmpdir.rb:89:in `mktmpdir'
     # /home/user/.gem/ruby/2.5.0/bin/gems/vimrunner-0.3.4/lib/vimrunner/rspec.rb:50:in `block (2 levels) in <top (required)>'
     # /home/user/.gem/ruby/2.5.0/bin/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'
     …
     # /usr/bin/bundle:23:in `load'
     # /usr/bin/bundle:23:in `<main>'
     # 
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

Finished in 1.12 seconds (files took 0.07848 seconds to load)
2 examples, 2 failures, 1 error occurred outside of examples
```
